import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/layout/Container";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { TechBadge } from "@/components/ui/TechBadge";
import { getProjectBySlug, projects } from "@/data/projects";
const labels = { producao: "Em produção", conceito: "Conceito em desenvolvimento", prototipo: "Protótipos", experimento: "Experimentos" };
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { return params.then(({ slug }) => { const project = getProjectBySlug(slug); return project ? { title: project.title, description: project.description, alternates: { canonical: project.href }, openGraph: { type: "article" as const, url: project.href, title: project.title, description: project.description, images: [{ url: project.image, alt: `Imagem ilustrativa do projeto ${project.title}` }] } } : { title: "Projeto" }; }); }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = getProjectBySlug(slug); if (!project) notFound(); return <><Navbar /><main id="conteudo-principal"><section className="section"><Container><Link href="/projects" className="text-sm text-slate-300 hover:text-white">← Todos os projetos</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">{project.category} · {labels[project.kind]}</p><h1 className="mt-5 text-pretty text-4xl font-semibold tracking-tight text-white sm:text-6xl">{project.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.technologies.map((technology) => <TechBadge key={technology}>{technology}</TechBadge>)}</div></div><div className="relative aspect-[16/10] overflow-hidden rounded-2xl border border-white/10 bg-surface"><Image src={project.image} alt={`Imagem ilustrativa do projeto ${project.title}`} fill className="object-cover" /></div></div></Container></section><section className="section bg-[#09101c]"><Container className="max-w-4xl"><div className="grid gap-10"><CaseBlock title="Contexto" content={project.caseStudy.context} /><CaseBlock title="Problema" content={project.caseStudy.problem} /><CaseBlock title="Objetivo" content={project.caseStudy.objective} /><CaseBlock title="Meu papel" content={project.caseStudy.role} /><CaseBlock title="Tecnologias e arquitetura" content={project.caseStudy.architecture} /><div><h2 className="text-2xl font-semibold text-white">Decisões técnicas</h2><ul className="mt-5 space-y-3 text-muted">{project.caseStudy.technicalDecisions.map((decision) => <li key={decision} className="border-l border-accent pl-4 leading-7">{decision}</li>)}</ul></div><CaseBlock title="Resultados / aprendizados" content={project.caseStudy.learnings} /><div><h2 className="text-2xl font-semibold text-white">Galeria</h2><p className="mt-4 text-muted">TODO: adicionar imagens e registros visuais deste projeto.</p></div></div></Container></section></main><Footer /></>; }
function CaseBlock({ title, content }: { title: string; content: string }) { return <div><h2 className="text-2xl font-semibold text-white">{title}</h2><p className="mt-4 whitespace-pre-line leading-7 text-muted">{content}</p></div>; }
